apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  steps:
    - name: npm-install
      image: node:16
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-test
spec:
  steps:
    - name: run-jasmine
      image: node:16
      script: |
        npx jasmine